apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: test-ogg-asyncapi
spec:
  type: asyncapi
  lifecycle: production
  owner: fintechdigitalventure/b2c-finserv-squad-hades
  definition:
    $text: ../asyncapi/asyncapi.yaml
